#!/usr/bin/env ruby

retried = false
begin
  require 'bako'
  require 'bako/cli'
rescue LoadError
  $:.unshift File.expand_path(File.join(__dir__, '..', 'lib'))
  if retried
    raise
  else
    retried = true
    retry
  end
end

Bako::CLI.start(ARGV)
